hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    user-service:
        path: /user/**
        url: http://localhost:5000
        stripPrefix: false
        sensitiveHeaders:

    item-service:
        path: /item/**
        url: http://localhost:5001
        stripPrefix: false
        sensitiveHeaders:

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 4000
