eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  context-path: /item
  port: 5001

application:
  files.localpath: E:\nginx\html
  access_base_url: http://image.taotao.com